# Generated by Django 5.2.4 on 2025-07-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_urls', models.TextField()),
                ('property_type', models.CharField(max_length=100)),
                ('dept_code', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('insee_code', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('blur_radius', models.FloatField(blank=True, null=True)),
                ('marketing_type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('surface', models.FloatField()),
                ('condominium_expenses', models.FloatField(blank=True, null=True)),
                ('caretaker', models.BooleanField(blank=True, null=True)),
                ('heating_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('water_heating_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('elevator', models.BooleanField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('floor_count', models.IntegerField(blank=True, null=True)),
                ('lot_count', models.IntegerField(blank=True, null=True)),
                ('construction_year', models.IntegerField(blank=True, null=True)),
                ('building_type', models.CharField(blank=True, max_length=100, null=True)),
                ('parking', models.BooleanField(blank=True, null=True)),
                ('parking_count', models.IntegerField(blank=True, null=True)),
                ('terrace', models.BooleanField(blank=True, null=True)),
                ('terrace_surface', models.FloatField(blank=True, null=True)),
                ('swimming_pool', models.BooleanField(blank=True, null=True)),
                ('garden', models.BooleanField(blank=True, null=True)),
                ('standing', models.CharField(blank=True, max_length=100, null=True)),
                ('new_build', models.BooleanField(blank=True, null=True)),
                ('small_building', models.BooleanField(blank=True, null=True)),
                ('corner_building', models.BooleanField(blank=True, null=True)),
                ('publication_start_date', models.DateField(blank=True, null=True)),
                ('dealer_name', models.CharField(max_length=255)),
                ('dealer_type', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('energy_classification', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
