# Generated by Django 5.2.4 on 2025-07-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniCopro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='surface',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
